name: Maven Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Configure Git user
        run: |
          git config user.email "jandroav@icloud.com"
          git config user.name "jandroav"

      - name: Prepare and Perform Maven Release
        run: |
          mvn -B release:clean release:prepare release:perform -Darguments="-Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true" -Dusername=jandroav -Dpassword=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

